apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-serivce
    app: voting-app
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    labels:
    name: postgres-pod
    app: voting-app
