apiVersion: v1
kind:  ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: my-app

spec:
  template:
    metadata:
      name: myapp-pod
      labels:
        app-name: testing-app
    spec:
      containers:
        - name: nginx-app
          image: nginx
  replicas: 3